#!/usr/bin/env bash

remote="$1"
url="$2"

zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')

while read local_ref local_oid remote_ref remote_oid
do
	if test "$local_oid" = "$zero"
	then
		# Handle delete
		:
	else
		if test "$remote_oid" = "$zero"
		then
			# New branch, examine all commits
			range="$local_oid"
		else
			# Update to existing branch, examine new commits
			range="$remote_oid..$local_oid"
		fi

		# Check that tests and lints run
		npm run build && npm run lint && CI=true npm run test:main
		if [ $? -ne 0 ]; then
			echo "pre-push hook failed with exit status $?"
			exit 1
		fi
	fi
done

exit 0
