#!/usr/bin/env bash

if ! ( npm run build --workspace=packages && npm run lint --workspace=packages && CI=true npm run test --workspace=packages/main ) ; then
	echo "pre-push hook failed with exit status $?"
	exit 1
fi
